/** @file temper-hum-hid-cmd.h
 *  @brief The header file for the command line option parser
 *  generated by GNU Gengetopt version 2.22.4
 *  http://www.gnu.org/software/gengetopt.
 *  DO NOT modify this file, since it can be overwritten
 *  @author GNU Gengetopt by Lorenzo Bettini */

#ifndef TEMPER_HUM_HID_CMD_H
#define TEMPER_HUM_HID_CMD_H

/* If we use autoconf.  */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <stdio.h> /* for FILE */

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#ifndef CMDLINE_PARSER_PACKAGE
/** @brief the program name (used for printing errors) */
#define CMDLINE_PARSER_PACKAGE "temper-hum-hid"
#endif

#ifndef CMDLINE_PARSER_PACKAGE_NAME
/** @brief the complete program name (used for help and version) */
#define CMDLINE_PARSER_PACKAGE_NAME "temper-hum-hid"
#endif

#ifndef CMDLINE_PARSER_VERSION
/** @brief the program version */
#define CMDLINE_PARSER_VERSION "v.0.2"
#endif

/** @brief Where the command line options are stored */
struct gengetopt_args_info
{
  const char *help_help; /**< @brief Print help and exit help description.  */
  const char *version_help; /**< @brief Print version and exit help description.  */
  char * verbose_arg;	/**< @brief Print debug messages, to standard output if no filename given (default='').  */
  char * verbose_orig;	/**< @brief Print debug messages, to standard output if no filename given original value given at command line.  */
  const char *verbose_help; /**< @brief Print debug messages, to standard output if no filename given help description.  */
  int syslog_flag;	/**< @brief Log debug messages to syslog (default=off).  */
  const char *syslog_help; /**< @brief Log debug messages to syslog help description.  */
  char * log_arg;	/**< @brief Log data to log file.  */
  char * log_orig;	/**< @brief Log data to log file original value given at command line.  */
  const char *log_help; /**< @brief Log data to log file help description.  */
  char * out_arg;	/**< @brief Output results to a file instead of printing it on screen, can be used for creating a status file which always has latest measurments.  */
  char * out_orig;	/**< @brief Output results to a file instead of printing it on screen, can be used for creating a status file which always has latest measurments original value given at command line.  */
  const char *out_help; /**< @brief Output results to a file instead of printing it on screen, can be used for creating a status file which always has latest measurments help description.  */
  int repeat_arg;	/**< @brief Constantly print results, repeat every given amount of seconds, devices will be reopened every 1 hour in this mode, 0 for no repeat (default='0').  */
  char * repeat_orig;	/**< @brief Constantly print results, repeat every given amount of seconds, devices will be reopened every 1 hour in this mode, 0 for no repeat original value given at command line.  */
  const char *repeat_help; /**< @brief Constantly print results, repeat every given amount of seconds, devices will be reopened every 1 hour in this mode, 0 for no repeat help description.  */
  int machine_flag;	/**< @brief Output in machine-friendly format, which is easier to be parsed by bash scripts for later use in monitoring tools, 4ex. Zabbix (default=off).  */
  const char *machine_help; /**< @brief Output in machine-friendly format, which is easier to be parsed by bash scripts for later use in monitoring tools, 4ex. Zabbix help description.  */
  
  unsigned int help_given ;	/**< @brief Whether help was given.  */
  unsigned int version_given ;	/**< @brief Whether version was given.  */
  unsigned int verbose_given ;	/**< @brief Whether verbose was given.  */
  unsigned int syslog_given ;	/**< @brief Whether syslog was given.  */
  unsigned int log_given ;	/**< @brief Whether log was given.  */
  unsigned int out_given ;	/**< @brief Whether out was given.  */
  unsigned int repeat_given ;	/**< @brief Whether repeat was given.  */
  unsigned int machine_given ;	/**< @brief Whether machine was given.  */

} ;

/** @brief The additional parameters to pass to parser functions */
struct cmdline_parser_params
{
  int override; /**< @brief whether to override possibly already present options (default 0) */
  int initialize; /**< @brief whether to initialize the option structure gengetopt_args_info (default 1) */
  int check_required; /**< @brief whether to check that all required options were provided (default 1) */
  int check_ambiguity; /**< @brief whether to check for options already specified in the option structure gengetopt_args_info (default 0) */
  int print_errors; /**< @brief whether getopt_long should print an error message for a bad option (default 1) */
} ;

/** @brief the purpose string of the program */
extern const char *gengetopt_args_info_purpose;
/** @brief the usage string of the program */
extern const char *gengetopt_args_info_usage;
/** @brief all the lines making the help output */
extern const char *gengetopt_args_info_help[];

/**
 * The command line parser
 * @param argc the number of command line options
 * @param argv the command line options
 * @param args_info the structure where option information will be stored
 * @return 0 if everything went fine, NON 0 if an error took place
 */
int cmdline_parser (int argc, char **argv,
  struct gengetopt_args_info *args_info);

/**
 * The command line parser (version with additional parameters - deprecated)
 * @param argc the number of command line options
 * @param argv the command line options
 * @param args_info the structure where option information will be stored
 * @param override whether to override possibly already present options
 * @param initialize whether to initialize the option structure my_args_info
 * @param check_required whether to check that all required options were provided
 * @return 0 if everything went fine, NON 0 if an error took place
 * @deprecated use cmdline_parser_ext() instead
 */
int cmdline_parser2 (int argc, char **argv,
  struct gengetopt_args_info *args_info,
  int override, int initialize, int check_required);

/**
 * The command line parser (version with additional parameters)
 * @param argc the number of command line options
 * @param argv the command line options
 * @param args_info the structure where option information will be stored
 * @param params additional parameters for the parser
 * @return 0 if everything went fine, NON 0 if an error took place
 */
int cmdline_parser_ext (int argc, char **argv,
  struct gengetopt_args_info *args_info,
  struct cmdline_parser_params *params);

/**
 * Save the contents of the option struct into an already open FILE stream.
 * @param outfile the stream where to dump options
 * @param args_info the option struct to dump
 * @return 0 if everything went fine, NON 0 if an error took place
 */
int cmdline_parser_dump(FILE *outfile,
  struct gengetopt_args_info *args_info);

/**
 * Save the contents of the option struct into a (text) file.
 * This file can be read by the config file parser (if generated by gengetopt)
 * @param filename the file where to save
 * @param args_info the option struct to save
 * @return 0 if everything went fine, NON 0 if an error took place
 */
int cmdline_parser_file_save(const char *filename,
  struct gengetopt_args_info *args_info);

/**
 * Print the help
 */
void cmdline_parser_print_help(void);
/**
 * Print the version
 */
void cmdline_parser_print_version(void);

/**
 * Initializes all the fields a cmdline_parser_params structure 
 * to their default values
 * @param params the structure to initialize
 */
void cmdline_parser_params_init(struct cmdline_parser_params *params);

/**
 * Allocates dynamically a cmdline_parser_params structure and initializes
 * all its fields to their default values
 * @return the created and initialized cmdline_parser_params structure
 */
struct cmdline_parser_params *cmdline_parser_params_create(void);

/**
 * Initializes the passed gengetopt_args_info structure's fields
 * (also set default values for options that have a default)
 * @param args_info the structure to initialize
 */
void cmdline_parser_init (struct gengetopt_args_info *args_info);
/**
 * Deallocates the string fields of the gengetopt_args_info structure
 * (but does not deallocate the structure itself)
 * @param args_info the structure to deallocate
 */
void cmdline_parser_free (struct gengetopt_args_info *args_info);

/**
 * Checks that all the required options were specified
 * @param args_info the structure to check
 * @param prog_name the name of the program that will be used to print
 *   possible errors
 * @return
 */
int cmdline_parser_required (struct gengetopt_args_info *args_info,
  const char *prog_name);


#ifdef __cplusplus
}
#endif /* __cplusplus */
#endif /* TEMPER_HUM_HID_CMD_H */
